import streamlit as st
import streamlit.components.v1 as components
import pandas as pd
import requests
import json
import os

st.set_page_config(
    page_title="Master Hub Trading Dashboard",
    page_icon="📈",
    layout="wide"
)

# Admin Owner Header
st.markdown("""
    <div style="background-color: #161b22; padding: 12px 20px; border-radius: 8px; border: 1px solid #30363d; margin-bottom: 20px; display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 10px;">
        <div>
            <span style="color: #8b949e; font-size: 13px;">Admin Owner:</span><br>
            <span style="color: #ffffff; font-size: 16px; font-weight: bold;">Sanjay Rana</span>
        </div>
        <div>
            <span style="color: #8b949e; font-size: 13px;">Contact Number:</span><br>
            <span style="color: #00ffcc; font-size: 16px; font-weight: bold;">8930814389</span>
        </div>
        <div>
            <span style="color: #8b949e; font-size: 13px;">PIN Number:</span><br>
            <span style="color: #00ffcc; font-size: 16px; font-weight: bold;">0000</span>
        </div>
    </div>
""", unsafe_allow_html=True)

st.title("🛡️ Master Hub: Algorithmic Trading & Live Monitoring Dashboard")
st.markdown("Strictly synchronized with `bot_status.json` file output.")

# Function to read directly from bot_status.json generated by your bot
def get_exact_bot_data():
    if os.path.exists("bot_status.json"):
        try:
            with open("bot_status.json", "r") as f:
                data = json.load(f)
                return data, "Loaded from bot_status.json"
        except Exception as e:
            return None, f"Error reading json: {e}"
    return None, "bot_status.json not found in repository!"

bot_data, status_msg = get_exact_bot_data()

if bot_data:
    btc_price_display = bot_data.get('btc_price', 'N/A')
    direction_display = bot_data.get('supertrend_direction', 'N/A')
    entry_display = bot_data.get('entry_price', 'N/A')
    t1_display = bot_data.get('target_1', 'N/A')
    t2_display = bot_data.get('target_2', 'N/A')
    t3_display = bot_data.get('target_3', 'N/A')
    active_members_count = bot_data.get('active_members', 0)
    trades_list = bot_data.get('trades', [])
else:
    btc_price_display = "⚠️ Missing Data"
    direction_display = "WAITING FOR BOT"
    entry_display = "0.00"
    t1_display = "0.00"
    t2_display = "0.00"
    t3_display = "0.00"
    active_members_count = 0
    trades_list = []

# Top Metrics Row
col1, col2, col3, col4 = st.columns(4)
col1.metric("Connected Exchange", "Delta Exchange", "API Active")
col2.metric("Active Members / Users", str(active_members_count), "System Log")
col3.metric("BTCUSDT Bot Price", f"${btc_price_display}", "From Bot File")
col4.metric("SuperTrend Signal", direction_display)

if not bot_data:
    st.error(f"⚠️ {status_msg} — कृपया सुनिश्चित करें कि आपका `delta_futures_bot.py` रन होकर गिटहब पर `bot_status.json` फाइल को अपडेट कर रहा है।")

st.markdown("---")

left_column, right_column = st.columns([2, 1])

with left_column:
    st.subheader("📈 Original TradingView Live Chart (BTCUSDT)")
    tradingview_widget = """
    <div class="tradingview-widget-container" style="height:500px;width:100%">
      <div id="tradingview_advanced_chart" style="height:100%;width:100%"></div>
      <script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
      <script type="text/javascript">
      new TradingView.widget(
      {
        "width": "100%",
        "height": 500,
        "symbol": "BINANCE:BTCUSDT",
        "interval": "5",
        "timezone": "Asia/Kolkata",
        "theme": "dark",
        "style": "1",
        "locale": "en",
        "toolbar_bg": "#f1f3f6",
        "enable_publishing": false,
        "hide_side_toolbar": false,
        "allow_symbol_change": true,
        "details": true,
        "studies": ["SuperTrend@tv-basicstudies"],
        "container_id": "tradingview_advanced_chart"
      });
      </script>
    </div>
    """
    components.html(tradingview_widget, height=520)

with right_column:
    st.subheader("⚡ Bot Entry & 3 Targets")
    st.info(f"🧭 **Direction:** {direction_display}")
    st.success(f"📥 **Entry Price:** ${entry_display}")
    st.warning(f"🎯 **Target 1:** ${t1_display}")
    st.warning(f"🎯 **Target 2:** ${t2_display}")
    st.warning(f"🎯 **Target 3:** ${t3_display}")
    
    st.subheader("🔌 Connection Details")
    st.write("• Exchange: **Delta Exchange India**")
    st.write(f"• Active Members: **{active_members_count}**")
    st.write("• Account Owner: **Sanjay Rana (8930814389)**")

st.markdown("---")

st.subheader("📊 Live Execution & Trade Book")
if trades_list:
    st.dataframe(pd.DataFrame(trades_list), use_container_width=True)
else:
    st.info("No active trades found in `bot_status.json`. Bot needs to push trade state.")
      
